controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

tic_tac_toe.home:
    path: /
    controller: App\Controller\TicTacToeController::index

tic_tac_toe.menu:
    path: /init-game
    controller: App\Controller\TicTacToeController::initGame

tic_tac_toe.game:
    path: /play
    controller: App\Controller\TicTacToeController::play